name: Release
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn ci
      - run: yarn lint
      - run: yarn formatcheck
      - run: yarn build
      - run: yarn test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          MERCHANT_NUMBER: ${{ secrets.MERCHANT_NUMBER }}
          MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
          PUBKEY: ${{ secrets.PUBKEY }}
          PRIVKEY: ${{ secrets.PRIVKEY }}

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
